//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Oferta
    {
        public int id_oferta { get; set; }
        public Nullable<int> id_lugar { get; set; }
        public string codigo_producto { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<decimal> precio { get; set; }
    
        public virtual Lugar Lugar { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
